// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Infrastructure.Persistence;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324085506_AddCustomerMaster")]
    partial class AddCustomerMaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Features.Auth.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("backend.Features.Auth.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("backend.Features.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("Mobile")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("backend.Features.Masters.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("backend.Features.Masters.Currencies.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("currencies", (string)null);
                });

            modelBuilder.Entity("backend.Features.Masters.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LedgerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LedgerId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("backend.Features.Masters.Customers.CustomerOpeningBalance", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<string>("BalanceType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerId");

                    b.ToTable("customer_opening_balances", (string)null);
                });

            modelBuilder.Entity("backend.Features.Masters.Ledgers.Ledger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("AllowManualPosting")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DefaultCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBillWise")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LedgerGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DefaultCurrencyId");

                    b.HasIndex("LedgerGroupId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ledgers", (string)null);
                });

            modelBuilder.Entity("backend.Features.Masters.Ledgers.LedgerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentGroupId");

                    b.ToTable("ledger_groups", (string)null);
                });

            modelBuilder.Entity("backend.Features.Masters.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("backend.Features.Masters.Products.ProductOpeningStock", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProductId");

                    b.ToTable("product_opening_stocks", (string)null);
                });

            modelBuilder.Entity("backend.Features.Masters.Taxes.Tax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("taxes", (string)null);
                });

            modelBuilder.Entity("backend.Features.Masters.Taxes.TaxSlab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("FromAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TaxId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ToAmount")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TaxId");

                    b.ToTable("tax_slabs", (string)null);
                });

            modelBuilder.Entity("backend.Features.Masters.Uoms.Uom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("uoms", (string)null);
                });

            modelBuilder.Entity("backend.Features.Masters.Vendors.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LedgerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LedgerId");

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("backend.Features.Masters.Vendors.VendorOpeningBalance", b =>
                {
                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<string>("BalanceType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VendorId");

                    b.ToTable("vendor_opening_balances", (string)null);
                });

            modelBuilder.Entity("backend.Features.Masters.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("backend.Features.Auth.User", b =>
                {
                    b.HasOne("backend.Features.Auth.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Features.Auth.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Features.Masters.Categories.Category", b =>
                {
                    b.HasOne("backend.Features.Masters.Categories.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("backend.Features.Masters.Customers.Customer", b =>
                {
                    b.HasOne("backend.Features.Masters.Ledgers.Ledger", "Ledger")
                        .WithMany()
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("backend.Features.Masters.Customers.CustomerBasicDetails", "BasicDetails", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Alias")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("alias");

                            b1.Property<string>("Category")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("category");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("code");

                            b1.Property<string>("CustomerType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("customer_type");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("name");

                            b1.HasKey("CustomerId");

                            b1.HasIndex("Code")
                                .IsUnique();

                            b1.HasIndex("Name")
                                .IsUnique();

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("backend.Features.Masters.Customers.CustomerBillingAddress", "BillingAddress", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("billing_city");

                            b1.Property<string>("Country")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("billing_country");

                            b1.Property<string>("Pincode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("billing_pincode");

                            b1.Property<string>("State")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("billing_state");

                            b1.Property<string>("Street")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("billing_street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("backend.Features.Masters.Customers.CustomerContact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("email");

                            b1.Property<string>("Mobile")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("mobile");

                            b1.Property<string>("Phone")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("phone");

                            b1.Property<string>("Website")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("website");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("backend.Features.Masters.Customers.CustomerFinancials", "Financials", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("CreditDays")
                                .HasColumnType("integer")
                                .HasColumnName("credit_days");

                            b1.Property<decimal?>("CreditLimit")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("credit_limit");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("backend.Features.Masters.Customers.CustomerSalesAndPricing", "SalesAndPricing", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("DefaultTaxId")
                                .HasColumnType("uuid")
                                .HasColumnName("default_tax_id");

                            b1.Property<string>("PriceLevel")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("price_level");

                            b1.HasKey("CustomerId");

                            b1.HasIndex("DefaultTaxId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasOne("backend.Features.Masters.Taxes.Tax", "DefaultTax")
                                .WithMany()
                                .HasForeignKey("DefaultTaxId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.Navigation("DefaultTax");
                        });

                    b.OwnsOne("backend.Features.Masters.Customers.CustomerStatusDetails", "StatusDetails", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Remarks")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("remarks");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsMany("backend.Features.Masters.Customers.CustomerShippingAddress", "ShippingAddresses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("country");

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean")
                                .HasColumnName("is_default");

                            b1.Property<string>("Name")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.Property<string>("Pincode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("pincode");

                            b1.Property<string>("State")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("state");

                            b1.Property<string>("Street")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("street");

                            b1.Property<Guid>("customer_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("customer_id");

                            b1.ToTable("customer_shipping_addresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("customer_id");
                        });

                    b.OwnsMany("backend.Features.Masters.Customers.CustomerTaxDocument", "TaxDocuments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("EffectiveFrom")
                                .HasColumnType("date")
                                .HasColumnName("effective_from");

                            b1.Property<DateOnly?>("EffectiveTo")
                                .HasColumnType("date")
                                .HasColumnName("effective_to");

                            b1.Property<string>("FilingFrequency")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("filing_frequency");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("number");

                            b1.Property<string>("State")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("state");

                            b1.Property<string>("TaxType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("tax_type");

                            b1.Property<bool>("Verified")
                                .HasColumnType("boolean")
                                .HasColumnName("verified");

                            b1.Property<DateOnly?>("VerifiedAt")
                                .HasColumnType("date")
                                .HasColumnName("verified_at");

                            b1.Property<Guid>("customer_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("customer_id");

                            b1.ToTable("customer_tax_documents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("customer_id");
                        });

                    b.Navigation("BasicDetails")
                        .IsRequired();

                    b.Navigation("BillingAddress")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Financials")
                        .IsRequired();

                    b.Navigation("Ledger");

                    b.Navigation("SalesAndPricing")
                        .IsRequired();

                    b.Navigation("ShippingAddresses");

                    b.Navigation("StatusDetails")
                        .IsRequired();

                    b.Navigation("TaxDocuments");
                });

            modelBuilder.Entity("backend.Features.Masters.Customers.CustomerOpeningBalance", b =>
                {
                    b.HasOne("backend.Features.Masters.Customers.Customer", "Customer")
                        .WithOne("OpeningBalance")
                        .HasForeignKey("backend.Features.Masters.Customers.CustomerOpeningBalance", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("backend.Features.Masters.Ledgers.Ledger", b =>
                {
                    b.HasOne("backend.Features.Masters.Currencies.Currency", "DefaultCurrency")
                        .WithMany()
                        .HasForeignKey("DefaultCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Features.Masters.Ledgers.LedgerGroup", "LedgerGroup")
                        .WithMany("Ledgers")
                        .HasForeignKey("LedgerGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultCurrency");

                    b.Navigation("LedgerGroup");
                });

            modelBuilder.Entity("backend.Features.Masters.Ledgers.LedgerGroup", b =>
                {
                    b.HasOne("backend.Features.Masters.Ledgers.LedgerGroup", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("backend.Features.Masters.Products.Product", b =>
                {
                    b.OwnsOne("backend.Features.Masters.Products.ProductAdditionalDetails", "AdditionalDetails", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Addition")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("addition");

                            b1.Property<decimal?>("AdditionPercentage")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("addition_percentage");

                            b1.Property<string>("Barcode")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("barcode");

                            b1.Property<string>("Company")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("company");

                            b1.Property<string>("CompanyStock")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("company_stock");

                            b1.Property<string>("Document")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("document");

                            b1.Property<decimal?>("PackUnit")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("pack_unit");

                            b1.Property<string>("PurchaseHistory")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("purchase_history");

                            b1.Property<string>("SalesHistory")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("sales_history");

                            b1.Property<string>("WarehouseStock")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("warehouse_stock");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("backend.Features.Masters.Products.ProductBasicInfo", "BasicInfo", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("name");

                            b1.Property<string>("OtherLanguage")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("other_language");

                            b1.Property<Guid?>("TaxId")
                                .HasColumnType("uuid")
                                .HasColumnName("tax_id");

                            b1.HasKey("ProductId");

                            b1.HasIndex("Code")
                                .IsUnique();

                            b1.HasIndex("Name")
                                .IsUnique();

                            b1.HasIndex("TaxId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.HasOne("backend.Features.Masters.Taxes.Tax", "Tax")
                                .WithMany()
                                .HasForeignKey("TaxId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.Navigation("Tax");
                        });

                    b.OwnsOne("backend.Features.Masters.Products.ProductPricingAndRates", "PricingAndRates", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("cost");

                            b1.Property<decimal?>("Mrp")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("mrp");

                            b1.Property<decimal?>("NormalRate")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("normal_rate");

                            b1.Property<decimal?>("ProfitPercentage")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("profit_percentage");

                            b1.Property<decimal?>("PurchaseRate")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("purchase_rate");

                            b1.Property<decimal?>("SalesRate")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("sales_rate");

                            b1.Property<decimal?>("WholesaleRate")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("wholesale_rate");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("backend.Features.Masters.Products.ProductProperties", "Properties", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("backend.Features.Masters.Products.ProductCategorization", "Categorization", b2 =>
                                {
                                    b2.Property<Guid>("ProductPropertiesProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Brand")
                                        .HasMaxLength(120)
                                        .HasColumnType("character varying(120)")
                                        .HasColumnName("brand");

                                    b2.Property<Guid?>("GroupCategoryId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("group_category_id");

                                    b2.Property<Guid?>("SubGroupCategoryId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("sub_group_category_id");

                                    b2.Property<Guid?>("VendorId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("vendor_id");

                                    b2.HasKey("ProductPropertiesProductId");

                                    b2.HasIndex("GroupCategoryId");

                                    b2.HasIndex("SubGroupCategoryId");

                                    b2.HasIndex("VendorId");

                                    b2.ToTable("products");

                                    b2.HasOne("backend.Features.Masters.Categories.Category", "GroupCategory")
                                        .WithMany()
                                        .HasForeignKey("GroupCategoryId")
                                        .OnDelete(DeleteBehavior.Restrict);

                                    b2.WithOwner()
                                        .HasForeignKey("ProductPropertiesProductId");

                                    b2.HasOne("backend.Features.Masters.Categories.Category", "SubGroupCategory")
                                        .WithMany()
                                        .HasForeignKey("SubGroupCategoryId")
                                        .OnDelete(DeleteBehavior.Restrict);

                                    b2.HasOne("backend.Features.Masters.Vendors.Vendor", "Vendor")
                                        .WithMany()
                                        .HasForeignKey("VendorId")
                                        .OnDelete(DeleteBehavior.Restrict);

                                    b2.Navigation("GroupCategory");

                                    b2.Navigation("SubGroupCategory");

                                    b2.Navigation("Vendor");
                                });

                            b1.OwnsOne("backend.Features.Masters.Products.ProductGeneralSettings", "GeneralSettings", b2 =>
                                {
                                    b2.Property<Guid>("ProductPropertiesProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("AutoEntry")
                                        .HasColumnType("boolean")
                                        .HasColumnName("auto_entry");

                                    b2.Property<bool>("CounterItem")
                                        .HasColumnType("boolean")
                                        .HasColumnName("counter_item");

                                    b2.Property<int>("ExpiryDays")
                                        .HasColumnType("integer")
                                        .HasColumnName("expiry_days");

                                    b2.Property<bool>("HideFromDevice")
                                        .HasColumnType("boolean")
                                        .HasColumnName("hide_from_device");

                                    b2.Property<bool>("Inactive")
                                        .HasColumnType("boolean")
                                        .HasColumnName("inactive");

                                    b2.Property<bool>("LessProfit")
                                        .HasColumnType("boolean")
                                        .HasColumnName("less_profit");

                                    b2.Property<bool>("SerialNo")
                                        .HasColumnType("boolean")
                                        .HasColumnName("serial_no");

                                    b2.Property<bool>("TaxInclusive")
                                        .HasColumnType("boolean")
                                        .HasColumnName("tax_inclusive");

                                    b2.HasKey("ProductPropertiesProductId");

                                    b2.ToTable("products");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductPropertiesProductId");
                                });

                            b1.Navigation("Categorization")
                                .IsRequired();

                            b1.Navigation("GeneralSettings")
                                .IsRequired();
                        });

                    b.OwnsOne("backend.Features.Masters.Products.ProductStockAndMeasurement", "StockAndMeasurement", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("BaseUomId")
                                .HasColumnType("uuid")
                                .HasColumnName("base_uom_id");

                            b1.Property<string>("Hsn")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("hsn");

                            b1.Property<decimal?>("MaximumStock")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("maximum_stock");

                            b1.Property<decimal?>("MinimumStock")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("minimum_stock");

                            b1.Property<Guid>("PurchaseUomId")
                                .HasColumnType("uuid")
                                .HasColumnName("purchase_uom_id");

                            b1.Property<decimal?>("ReOrderLevel")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("reorder_level");

                            b1.Property<decimal?>("ReOrderQuantity")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("reorder_quantity");

                            b1.Property<Guid>("SalesUomId")
                                .HasColumnType("uuid")
                                .HasColumnName("sales_uom_id");

                            b1.Property<Guid>("StockUomId")
                                .HasColumnType("uuid")
                                .HasColumnName("stock_uom_id");

                            b1.HasKey("ProductId");

                            b1.HasIndex("BaseUomId");

                            b1.HasIndex("PurchaseUomId");

                            b1.HasIndex("SalesUomId");

                            b1.HasIndex("StockUomId");

                            b1.ToTable("products");

                            b1.HasOne("backend.Features.Masters.Uoms.Uom", "BaseUom")
                                .WithMany()
                                .HasForeignKey("BaseUomId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.HasOne("backend.Features.Masters.Uoms.Uom", "PurchaseUom")
                                .WithMany()
                                .HasForeignKey("PurchaseUomId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.HasOne("backend.Features.Masters.Uoms.Uom", "SalesUom")
                                .WithMany()
                                .HasForeignKey("SalesUomId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.HasOne("backend.Features.Masters.Uoms.Uom", "StockUom")
                                .WithMany()
                                .HasForeignKey("StockUomId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("BaseUom");

                            b1.Navigation("PurchaseUom");

                            b1.Navigation("SalesUom");

                            b1.Navigation("StockUom");
                        });

                    b.Navigation("AdditionalDetails")
                        .IsRequired();

                    b.Navigation("BasicInfo")
                        .IsRequired();

                    b.Navigation("PricingAndRates")
                        .IsRequired();

                    b.Navigation("Properties")
                        .IsRequired();

                    b.Navigation("StockAndMeasurement")
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Features.Masters.Products.ProductOpeningStock", b =>
                {
                    b.HasOne("backend.Features.Masters.Products.Product", "Product")
                        .WithOne("OpeningStock")
                        .HasForeignKey("backend.Features.Masters.Products.ProductOpeningStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("backend.Features.Masters.Taxes.TaxSlab", b =>
                {
                    b.HasOne("backend.Features.Masters.Taxes.Tax", "Tax")
                        .WithMany("Slabs")
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("backend.Features.Masters.Vendors.Vendor", b =>
                {
                    b.HasOne("backend.Features.Masters.Ledgers.Ledger", "Ledger")
                        .WithMany()
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("backend.Features.Masters.Vendors.VendorAddressAndContact", "AddressAndContact", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("address");

                            b1.Property<string>("ContactName")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("contact_name");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("email");

                            b1.Property<string>("Fax")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("fax");

                            b1.Property<string>("Mobile")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("mobile");

                            b1.Property<string>("NameInOl")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name_in_ol");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("phone");

                            b1.Property<string>("Web")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("web");

                            b1.HasKey("VendorId");

                            b1.ToTable("vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsOne("backend.Features.Masters.Vendors.VendorBankDetails", "BankDetails", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AccountNo")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("account_no");

                            b1.Property<string>("BankAddress")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("bank_address");

                            b1.Property<string>("BankDetails")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("bank_details");

                            b1.HasKey("VendorId");

                            b1.ToTable("vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsOne("backend.Features.Masters.Vendors.VendorBasicInfo", "BasicInfo", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.Property<string>("Under")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("under");

                            b1.HasKey("VendorId");

                            b1.HasIndex("Code")
                                .IsUnique();

                            b1.HasIndex("Name")
                                .IsUnique();

                            b1.ToTable("vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsOne("backend.Features.Masters.Vendors.VendorCreditAndFinance", "CreditAndFinance", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("CreditLimit")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("credit_limit");

                            b1.Property<Guid?>("CurrencyId")
                                .HasColumnType("uuid")
                                .HasColumnName("currency_id");

                            b1.Property<int?>("DueDays")
                                .HasColumnType("integer")
                                .HasColumnName("due_days");

                            b1.Property<string>("PaymentTerms")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("payment_terms");

                            b1.Property<string>("Remark")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("remark");

                            b1.HasKey("VendorId");

                            b1.HasIndex("CurrencyId");

                            b1.ToTable("vendors");

                            b1.HasOne("backend.Features.Masters.Currencies.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("CurrencyId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner()
                                .HasForeignKey("VendorId");

                            b1.Navigation("Currency");
                        });

                    b.OwnsOne("backend.Features.Masters.Vendors.VendorOtherInfo", "Other", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Company")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("company");

                            b1.HasKey("VendorId");

                            b1.ToTable("vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsOne("backend.Features.Masters.Vendors.VendorTaxAndCompliance", "TaxAndCompliance", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Gstin")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("gstin");

                            b1.Property<string>("Tin")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("tin");

                            b1.HasKey("VendorId");

                            b1.ToTable("vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.Navigation("AddressAndContact")
                        .IsRequired();

                    b.Navigation("BankDetails")
                        .IsRequired();

                    b.Navigation("BasicInfo")
                        .IsRequired();

                    b.Navigation("CreditAndFinance")
                        .IsRequired();

                    b.Navigation("Ledger");

                    b.Navigation("Other")
                        .IsRequired();

                    b.Navigation("TaxAndCompliance")
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Features.Masters.Vendors.VendorOpeningBalance", b =>
                {
                    b.HasOne("backend.Features.Masters.Vendors.Vendor", "Vendor")
                        .WithOne("OpeningBalance")
                        .HasForeignKey("backend.Features.Masters.Vendors.VendorOpeningBalance", "VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("backend.Features.Masters.Categories.Category", b =>
                {
                    b.Navigation("ChildCategories");
                });

            modelBuilder.Entity("backend.Features.Masters.Customers.Customer", b =>
                {
                    b.Navigation("OpeningBalance");
                });

            modelBuilder.Entity("backend.Features.Masters.Ledgers.LedgerGroup", b =>
                {
                    b.Navigation("ChildGroups");

                    b.Navigation("Ledgers");
                });

            modelBuilder.Entity("backend.Features.Masters.Products.Product", b =>
                {
                    b.Navigation("OpeningStock");
                });

            modelBuilder.Entity("backend.Features.Masters.Taxes.Tax", b =>
                {
                    b.Navigation("Slabs");
                });

            modelBuilder.Entity("backend.Features.Masters.Vendors.Vendor", b =>
                {
                    b.Navigation("OpeningBalance");
                });
#pragma warning restore 612, 618
        }
    }
}
